# Generated by Django 5.0.1 on 2024-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
