apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ngnix
  template:
    metadata:
      labels:
        app: ngnix
    spec:
      containers:
      - name: todo-app
        image: mknnyk/django_todo_cicd:52${BUILD_NUMBER}
        ports:
        - containerPort: 8000

